# Generated by Django 5.0.7 on 2024-07-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lname',
            new_name='last_name',
        ),
    ]
