# Generated by Django 5.0.7 on 2024-08-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='photos/payment_proof'),
        ),
    ]
